!include make_cfg.mak

!ifndef MY_CXX
MY_CXX = cl
!endif

!ifndef MY_CXXFLAGS
MY_CXXFLAGS = "/I"$(PSDK)/include" /I"$(PSDK)\include/crt"  /I"$(PSDK)\include\mfc" /I"$(PSDK)\include\atl""
!endif

!ifndef MY_LINK
MY_LINK = link
!endif

!ifndef MY_LINKFLAGS
MY_LINKFLAGS = "/libpath:"$(PSDK)/lib" bufferoverflowu.lib"
!endif

!ifndef PLATFORM
PLATFORM = I386
!endif

!ifndef PDBNAME
PDBNAME = vc70.pdb
!endif

!ifndef DEBUG
DEBUG = 0
!endif

!include make_all_ms.mak
